Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  ### DB VM ###
  config.vm.define "db01" do |db01|
    db01.vm.box = "eurolinux-vagrant/centos-stream-9"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.55"
    db01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    db01.vm.provision "shell", path: "backend-stack.sh"
  end

  ### Web (Tomcat) VM - Ubuntu ###
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/jammy64"  # Ubuntu 22.04 LTS
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.51"
    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    web01.vm.provision "shell", path: "tomcat-provision.sh"
    # If running from WSL, disable default synced folder to avoid errors:
    web01.vm.synced_folder ".", "/vagrant", disabled: true    
  end

  ### Windows VM ###
  config.vm.define "win01" do |win01|
  config.vm.boot_timeout = 600
    win01.vm.box = "gusztavvargadr/windows-10"
    win01.vm.hostname = "win01"
    win01.vm.communicator = "winrm"
    win01.winrm.username = "vagrant"
    win01.winrm.password = "vagrant"
    win01.winrm.transport = :negotiate
    win01.vm.network "private_network", ip: "192.168.56.60"
    win01.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.gui = true
      vb.cpus = 2
    end
    win01.vm.communicator = "winrm"
    win01.vm.provision "shell", path: "windows-node.ps1", privileged: true
    win01.vm.synced_folder ".", "/vagrant", disabled: true
  end
end
