Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  ### DB VM ###
  config.vm.define "db01" do |db01|
    db01.vm.box = "eurolinux-vagrant/centos-stream-9"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.55"
    db01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    db01.vm.provision "shell", path: "backend-stack.sh"      
  end

  ### Web (Tomcat) VM - Now Ubuntu ###
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/jammy64"  # Ubuntu 22.04 LTS
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.51"
    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    web01.vm.provision "shell", path: "tomcat-provision.sh"
    # web01.vm.synced_folder ".", "/vagrant", disabled: true
  end
end
